### ISSUE TITLE
When used inside of a tab bar controller, and hiding the bottom bar on push, the destination controller has a gap at the bottom

### ISSUE THREAD

**Issue by 0xc00010ff** [Enricoza/EZCustomNavigation#4]
When using EZNavigationController on a navigation controller within a UITabBarController that has a controller with `hidesBottomBarWhenPushed` enabled, there is an effect where the destination view controller is not rendered at the bottom. This is only a problem during the animation, the controller looks correct when the animation is finished. The interactive pop also works perfectly.

![IMG_D2A9982CA9B1-1](https://user-images.githubusercontent.com/4950729/103868052-37121c80-507d-11eb-9342-67d181ba0bc9.jpeg)

**Comment by 0xc00010ff** [comment]
Great work by the way!

**Comment by Enricoza** [comment]
Hi Brian, thank your for taking the time to open this issue, it really helps.

I'm going to look into this by the end of the day or at max at the end of the week and get back to you asap.

To speed the process up, in the meantime, could you please send me a small example project in which you reproduce the issue?

**Comment by Enricoza** [comment]
Hi @0xc00010ff, have you had the time to create a small sample where I can reproduce the issue? If so you can also email it to me in private if you want.

I've tried to test with a `UITabBarController` that embedded my `EZNavigationController` with a root view controller and pushing onto this a new controller with `hidesBottomBarWhenPushed` set to true, but the effect looks perfect to me: The bottom bar slides away with the previous controller and the destination controller is never cut at the bottom.

Let me know if you can manage to send me this sample to reproduce the issue so I can help you as soon as possible.

**Comment by ReDetection** [comment]
I have this issue too and I was able to track it down to a custom setting on a tabbar:
```swift
tabbarController.tabbar.isTranslucent = false
```

Once I removed this line, the glitch disappeared 🎉

**Comment by Enricoza** [comment]
Thank you again @ReDetection,
I've been able to reproduce the issue thank to your discovery and although making the tabBar translucent resolves the issue it should be fixed anyway.

I'm working on a solution right know that will hopefully be included in the next release.

**Comment by Enricoza** [comment]
Hi @0xc00010ff and @ReDetection,
The new release ([v1.1.2](https://github.com/Enricoza/EZCustomNavigation/releases/tag/v1.1.2)) includes a fix for the translucent tabBar cutting the view controller that's being pushed.
Unfortunately the effect is not exactly the same as the navigation controller, (the tabBar doesn't follow my parallax percentage) but I didn't find a safe and clear way to do it. 
It seems to move at its own will.

In case you have any idea on what is going on , I'm more than happy to hear your thoughts and work at a better fix.
If you want, we can talk about it in this (#11) issue.

And thank you again for opening this issue and for investigating it with me.
